### ISSUE TITLE
Self closing tags are not recognized

### ISSUE THREAD

**Issue by timbo86** [DanielJDufour/xml-utils#1]
A xml of
`<fields>
    <field datatype="text" name="L101"/>  
    <field datatype="text" name="L101_1"/>  
    <field datatype="text" name="P102"/>  
    <field datatype="text" name="P102_1">  
        <source></source>  
        <param></param>  
    </field>  
    <field datatype="text" name="P103"></field>  
</fields>`
returns only an array of two fields with name P102_1 and P103 when using `findTagsByName(xml, 'field')` or `findTagsByPath(xml, 'field')`.
It should return an array of five elements, as self closing tag is a valid xml syntax.

**Comment by DanielJDufour** [comment]
I have a fix. Will merge soon.

**Comment by DanielJDufour** [comment]
fixed with https://github.com/DanielJDufour/xml-utils/pull/2.
will republish soon

**Comment by DanielJDufour** [comment]
new version 1.0.3 has been published.  please try again and let me know if it doesn't work. thanks again!
