### ISSUE TITLE
Commented out nodes are still added to the result

### ISSUE THREAD

**Issue by timbo86** [DanielJDufour/xml-utils#3]
Having a tag commented out like this:
![image](https://user-images.githubusercontent.com/65157059/172322943-72f168fb-ce71-457b-9a14-0770b90495a4.png)
Still adds this node to the result when using any of the find tag(s) by name or path functions.

This can't be worked around as the comment chars are not part of the results outer property and there is no additional flag property in the result, so that we can't tell apart if it was commented out or not.

**Comment by DanielJDufour** [comment]
could you pre-filter the lines before passing to xml-utils like

```js
let xml = "<fields>...";
let lines = xml.split("\n");
lines = lines.filter(line => !line.trim().startsWith("<!--"); // filter out lines that start with a comment indication
xml = lines.join("\n");

findTagsByPath(xml, ["fields", "field"])
```

Thoughts?

**Comment by timbo86** [comment]
How about multiline comments?
![image](https://user-images.githubusercontent.com/65157059/179691140-ec3642a0-4e8c-4991-ae32-8e1fa91437cb.png)

I think this should follow the same syntax with opening and closing tags, but instead of < and >, there is a

**Comment by DanielJDufour** [comment]
good point!  and thank you for showing the example.  I'm curious, what type of xml file is shown above?  Most of the XML files I deal with (except HTML) don't usually have comments.  But I agree if would be worth doing if you and others need it.

**Comment by DanielJDufour** [comment]
hi, @timbo86 .  I have a pr up for a new function that removes comments.  One could then use it like

```js
import { removeComments, findTagsByPath } from "xml-utils";

let xml = '<fields ...';

xml = removeComments(xml);

findTagsByPath(xml, ["fields", "field"]);
```

Could I get your review on https://github.com/DanielJDufour/xml-utils/pull/4?

**Comment by timbo86** [comment]
Okay, thanks. I will try it.

Just one question. Does this remove all comments, so I would only have to execute it once, or just in current tree level?

**Comment by DanielJDufour** [comment]
Hey, sorry I missed this.  That's a great question.  It removes all the comments at all depths, so you only have to execute it once.

**Comment by DanielJDufour** [comment]
fixed and republished.  thanks for all your help and ideas here :-)
