### ISSUE TITLE
Add esm compatibility

### ISSUE THREAD

**Issue by timbo86** [DanielJDufour/xml-utils#5]
When using vite, there is a workaround needed for commonjs. To avoid this, please add esm script modules compatibility.

It should be possible to have an hybrid cjs and esm module.

**Comment by DanielJDufour** [comment]
Good catch!

**Comment by DanielJDufour** [comment]
I published a new version as a release candidate, which I believe provides the esm support you require.  Could you try to install xml-utils as `npm install xml-utils@next` (or yarn add or pnpm install`) and let me know if it works now without the workaround.  Thank you!

**Comment by DanielJDufour** [comment]
@IvanSanchez , I merged you PR.  Thank you so much!  I then published a new patch release candidate, which you can install with `npm install xml-utils@next`.  Would you be able to try that out and confirm that it works for you?  I'll also need to confirm that it works with geotiff.js (which shouldn't take long).

Thank yoU!

**Comment by IvanSanchez** [comment]
@DanielJDufour I just run `npm install xml-utils@next`, which pulled version `1.7.1-0`. After a tiny bit of testing, it works as expected. :+1:

I'm preparing a more complex PR for geotiff.js for full in-browser ESM compatibility - involving :imp: dynamic `import`s :imp:.
